inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'doc/**/*'
    - 'log/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

require:
  - rubocop-rspec
  - rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 50
  Exclude:
    - 'spec/**/*.rb'
    - 'features/**/*.rb'

Metrics/BlockLength:
  CountComments: false
  Max: 50
  Exclude:
    - 'spec/**/*.rb'
    - 'features/**/*.rb'

RSpec/EmptyExampleGroup:
  Enabled: false
